from pathlib import Path
from typing import IO

import click
from loguru import logger

from bin_tools.bin_utils import find_binfiles
from bin_tools.dataclasses.binset import BinSet
from bin_tools.import_data.binset import parse_bins


@click.command("binset")
@click.option(
    "--compress",
    "-z",
    "compress",
    is_flag=True,
    help="(optional) Compress the output using zstd.",
)
@click.option(
    "--group",
    type=str,
    help="Name to give to the group of bins.",
    required=True,
)
@click.option(
    "--binsplit-separator",
    type=str,
    help="If bin was generated by SemiBin2, VAMB, or another binsplitting binner, the separator required to recover the original contig named.",
    required=False,
)
@click.option(
    "--rename-prefix",
    type=str,
    help="Prefix to use for renaming bins.",
    required=False,
)
@click.option("--output", "-o", type=click.File("wb"), default="-", required=False)
@click.argument("binfile", type=click.File("rb"), required=True, default="-")
@click.argument(
    "fasta",
    type=click.Path(exists=True, dir_okay=True, file_okay=True),
    nargs=-1,
    required=True,
)
def import_binset(
    binfile: IO,
    fasta: list[str],
    group: str,
    output: IO,
    compress: bool = False,
    rename_prefix: str | None = None,
    binsplit_separator: str | None = None,
):
    """Add a set of bins to a BINS file.

    BINFILE: a BINS file to add the bins to
    FASTA: a list of bin FASTA files, or alternatively a directories containing bin FASTA files
    """
    binset = BinSet.read_binfile(binfile)

    bin_directories_files = [
        find_binfiles(Path(dir)) for dir in fasta if Path(dir).is_dir()
    ]
    bins_direct_files = [Path(file) for file in fasta if Path(file).is_file()]
    bin_files = [
        item for sublist in bin_directories_files for item in sublist
    ] + bins_direct_files

    try:
        parsed_bins = parse_bins(
            bins=bin_files,
            group=group,
            asm_contigs=binset.contigs,
            rename_prefix=rename_prefix,
            binsplit_separator=binsplit_separator,
        )
    except RuntimeError as e:
        logger.error(f"Error: {e}")
        raise click.ClickException(f"Error: {e}")

    logger.info(f"Parsed {len(parsed_bins)} bins.")
    if logger.level == "DEBUG":
        for bin in parsed_bins:
            logger.debug(f"Parsed bin: {bin.id}")

    if binset.bins is None:
        binset.bins = parsed_bins
    else:
        binset.bins = binset.bins + parsed_bins
    binset.write_binfile(output, compress=compress)
